
        [Test]
        public void EcxeptionTest()
        {
            // 例外発生
            Assert.That(someMethod1, Throws.ArgumentException); // ArgumentExceptionは専用のプロパティが用意されている
            Assert.That(someMethod1, Throws.TypeOf&lt;ArgumentException&gt;());

            // メソッド定義をインラインで行う場合
            Assert.That(() =&gt; { someMethod1(); }, Throws.ArgumentException);
            Assert.That(() =&gt; { someMethod2(1, 2); }, Throws.ArgumentNullException); // 引数付きのメソッドは直接渡せないので、ラムダ式を利用する

            // プロパティ確認
            Assert.That(() =&gt; { someMethod2(1, 2); }, Throws.ArgumentNullException.With.Message.EqualTo("値を Null にすることはできません。")); // Messageは専用のプロパティが用意されている
            Assert.That(() =&gt; { someMethod2(1, 2); }, Throws.ArgumentNullException.With.Property("Message").EqualTo("値を Null にすることはできません。"));
        }

        public void someMethod1()
        {
            throw new ArgumentException();
        }

        public void someMethod2(int a, int b)
        {
            throw new ArgumentNullException();
        }

