
try
{
    Parallel.Invoke(
        () =&gt; throw new ArgumentException(),
        () =&gt; throw new InvalidOperationException(),
        () =&gt; throw new FormatException()
    );
}
catch (AggregateException ae)
{
    // 原因となった Exception を知りたい場合は
    // Flatten() や InnerExceptions が便利
    var exceptions = ae.Flatten().InnerExceptions;
    foreach (var ex in exceptions)
    {
        Debug.WriteLine(ex.GetType());
    }
}

