
Exception exStack = new Exception();
try
{
    // 何らかの処理
}
catch (Exception ex)
{
    exStack = ex;
}

ExceptionDispatchInfo.Capture(exStack).Throw();

