
    catch (Exception1)
    {
        // 原因を呼び出し元に伝える場合
        db.Rollback();
        throw;
    }
    catch (Exception2 ex)
    {
        // 原因の詳細がそれ以上必要ない場合
        Debug.WriteLine(ex.ToString());
        throw ex;
    }

