
                try
                {
                    ex.Handle(ex2 =&gt; {
                        // 例外ハンドリングを行ったが、"1-1"しかハンドリングできなかった
                        if (ex2.Message == "1-1")
                        {
                            return true;
                        }
                        // "1-2"を別の例外でラップしてthrowした場合
                        if (ex2.Message == "1-2")
                        {
                            throw new Exception("Handle Exception", ex2);
                        }
                        return false;
                    });
                }
                catch (AggregateException ex3)
                {
                    // ここ呼ばれない
                    Console.WriteLine("--- Unhandle InnerExceptions ---");
                    Console.WriteLine(string.Join("\n", ex3.InnerExceptions.Select(ex2str)));
                }

