
try
{
    // 例外が発生する可能性のある処理
}
catch(Exception e)
{
    // 例外に対応した処理
}

