
catch (例外1 e) {
    例外処理
}
catch (例外2 e) {
    例外処理
}

